import type { Metadata } from "next";
import { SUSE_Mono, Nunito } from "next/font/google";
import "./globals.css";

const suseMono = SUSE_Mono({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const nunito = Nunito({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Canchita | Turnos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="es"
      className={`${suseMono.variable} ${nunito.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-white text-[#243054]">
        {children}
      </body>
    </html>
  );
}
